// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG02abQAIj4rbKYO6M5hozSICPAr5pEqE',
    appId: '1:676801212255:web:7077b82b048feba25190ea',
    messagingSenderId: '676801212255',
    projectId: 'lati-games-68200',
    authDomain: 'lati-games-68200.firebaseapp.com',
    storageBucket: 'lati-games-68200.appspot.com',
    measurementId: 'G-2XZ41TXKWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-IFSpYQUq-n9Hv2zWZxU38WiBmW2FX8',
    appId: '1:676801212255:android:7732b4529ff749875190ea',
    messagingSenderId: '676801212255',
    projectId: 'lati-games-68200',
    storageBucket: 'lati-games-68200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6S-cO9EDbL24ZBA7vCox7C2bhJ4Ot3Vc',
    appId: '1:676801212255:ios:0d0a2eeabbcb74825190ea',
    messagingSenderId: '676801212255',
    projectId: 'lati-games-68200',
    storageBucket: 'lati-games-68200.appspot.com',
    iosBundleId: 'com.example.gameslati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG02abQAIj4rbKYO6M5hozSICPAr5pEqE',
    appId: '1:676801212255:web:4560c859d4acd22a5190ea',
    messagingSenderId: '676801212255',
    projectId: 'lati-games-68200',
    authDomain: 'lati-games-68200.firebaseapp.com',
    storageBucket: 'lati-games-68200.appspot.com',
    measurementId: 'G-GZMNSMYEBR',
  );
}
